package com.bancodealimentos.api_gateway.model;

import lombok.Data;

import java.math.BigDecimal;

@Data
public class DonacionDTO {  
    private Long id;
    private BigDecimal monto;  // Changed from Double to BigDecimal for monetary values
    private Long donanteId;   // Changed from String donante to Long donanteId to match schema
    private String fecha;     // Changed from LocalDate to String to match GraphQL schema
    
    // Getters and setters are generated by Lombok with @Data
}
